import { GeneralFormErrors, RewardFormErrors, TimePlaceFormErorrs } from "@/app/_components/Event/steps/types";
import { EventTicketType } from "@/db/schema";
import { EventDataSchemaAllOptional, PaidEventSchema, PaidEventType } from "@/types";
import type {} from "@redux-devtools/extension";
import { create } from "zustand";
import { devtools } from "zustand/middleware";
import { immer } from "zustand/middleware/immer";
// required for devtools typing

export type StoreEventData = Omit<EventDataSchemaAllOptional, "paid_event"> & {
  /*
   * These types are generated by event store And are dynamic
   */
  hasEnded: boolean;

  /*
   * These type are corrected to work with the schema
   */
  paid_event: Partial<PaidEventType> & {
    bought_capacity?: number;
  };
};

type PaidInfoErrors = {
  has_payment?: string[] | undefined;
  payment_recipient_address?: string[] | undefined;
  token_id?: string[] | undefined;
  payment_amount?: string[] | undefined;
  has_nft?: string[] | undefined;
  nft_title?: string[] | undefined;
  nft_description?: string[] | undefined;
  nft_image_url?: string[] | undefined;
  nft_video_url?: string[] | undefined;
  capacity?: string[] | undefined;
};

export type CreateEventStoreType = {
  currentStep: number;
  setCurrentStep: (_step: number) => void;
  eventData: StoreEventData;
  edit?: {
    eventHash?: string;
  };
  setEventData: (_data: Partial<StoreEventData>) => void;
  setEdit: (_edit: { eventHash?: string }) => void;
  resetState: () => void;

  // form errors
  generalStepErrors?: GeneralFormErrors;
  timeplaceStepErrors?: TimePlaceFormErorrs;
  rewardStepErrors?: RewardFormErrors;

  // set errors
  setGeneralStepErrors: (_: GeneralFormErrors) => void;
  setTimePlaceStepErrors: (_: TimePlaceFormErorrs) => void;
  setRewardStepErrors: (_: RewardFormErrors) => void;

  // clear errors
  clearGeneralStepErrors: () => void;
  clearRewardStepErrors: () => void;
  clearTimePlaceStepErrors: () => void;
  clearImageErrors: () => void;
  clearVideoErrors: () => void;
  resetReward: () => void;

  // REGISTRATION
  toggleHasRegistration: () => void;

  // WEB3 / SBT
  toggleHasWeb3: () => void;
  setHasWeb3: (enabled: boolean) => void;

  /**
   * PAID EVENT CREATION ACTIONS
   */
  togglePaidEvent: () => void;
  changePaymentToken: (tokenId: number) => void;
  changeTicketType: (ticketType: EventTicketType) => void;
  changePaymentAmount: (amount: number) => void;
  // --- // nft info
  changeNFTImage: (url: string) => void;
  changeNFTVideo: (url: string) => void;
  changeNFTTitle: (title: string) => void;
  changeNFTDescription: (desc: string) => void;

  /**** REGISTRATION STEP MAIN BUTTON CLICK ****/
  registrationStepMainButtonClick: (_recipient: string | null) => void;

  /**** ⭕ PAID EVENT INPUT ERRORS ⭕ ****/
  paid_info_errors: PaidInfoErrors;
  setPaidInfoErrors: (_key: keyof PaidInfoErrors, _value: any) => void;
};

const defaultState = {
  event: {
    dynamic_fields: [] as {
      type: string;
      title: string;
      description: string;
      emoji: string;
      id?: number | undefined;
      placeholder?: string | undefined;
      url?: string | undefined;
    }[],
    owner: 0,
    type: 0,
    has_web3: false,
    hasEnded: true,
    has_registration: false,
    has_approval: false,
    has_waiting_list: false,
    capacity: null,
    paid_event: {
      has_payment: false,
    },
  },
  step: 1,
};

export const useCreateEventStore = create<CreateEventStoreType>()(
  devtools(
    immer((set, get) => ({
      currentStep: defaultState.step,
      eventData: defaultState.event,
      paid_info_errors: {},
      clearImageErrors: () => {
        set((state) => ({
          ...state,
          generalStepErrors: { ...state.generalStepErrors, image_url: undefined },
        }));
      },
      clearVideoErrors: () => {
        set((state) => ({
          ...state,
          generalStepErrors: { ...state.generalStepErrors, video_url: undefined },
        }));
      },
      setGeneralStepErrors: (errors) => {
        set((state) => ({
          ...state,
          generalStepErrors: errors,
        }));
      },
      setTimePlaceStepErrors(errors) {
        set((state) => ({
          ...state,
          timeplaceStepErrors: errors,
        }));
      },
      setRewardStepErrors: (errors) => {
        set((state) => ({
          ...state,
          rewardStepErrors: errors,
        }));
      },
      clearGeneralStepErrors: () => {
        set((state) => {
          return {
            ...state,
            generalStepErrors: {},
          };
        });
      },
      clearTimePlaceStepErrors() {
        set((state) => {
          return {
            ...state,
            timeplaceStepErrors: {},
          };
        });
      },
      clearRewardStepErrors: () => {
        set((state) => ({
          ...state,
          rewardStepErrors: {},
        }));
      },
      setCurrentStep: (step: number) => set((state) => ({ ...state, currentStep: step })),
      setEventData: (data) =>
        set((state) => {
          const newData = {
            ...state.eventData,
            ...data,
          };

          if (newData.eventLocationType === "in_person") {
            newData.has_registration = true;
            if (newData.capacity === null || newData.capacity === undefined) {
              newData.capacity = 100;
            }
          }

          state.eventData = newData;
          state.eventData.hasEnded = !!(
            state.edit?.eventHash &&
            state?.eventData?.end_date &&
            state.eventData.end_date < Date.now() / 1000
          );
        }),
      setEdit: (edit: { eventHash?: string }) => set((state) => ({ ...state, edit })),

      resetState: () => {
        set(() => ({
          currentStep: defaultState.step,
          eventData: defaultState.event,
          edit: {},
        }));
      },
      resetReward: () => {
        set((state) => ({
          ...state,
          eventData: {
            capacity: null,
            has_waiting_list: false,
            has_approval: false,
            has_registration: false,
            ...state.eventData,
            video_url: "",
            ts_reward_url: "",
          },
        }));
      },
      toggleHasRegistration: () => {
        set((state) => {
          if (state.eventData.eventLocationType === "in_person") {
            state.eventData.has_registration = true;
            state.eventData.capacity =
              state.eventData.capacity && state.eventData.capacity >= 1 ? state.eventData.capacity : 100;
            return;
          }
          state.eventData.has_registration = !state.eventData.has_registration;
          if (state.eventData.has_registration) {
            state.eventData.paid_event.has_payment = false;
            state.eventData.capacity = null;
          } else {
            state.eventData.capacity = null;
          }
        });
      },
      toggleHasWeb3: () => {
        set((state) => {
          const enabled = !state.eventData.has_web3;
          state.eventData.has_web3 = enabled;
          if (!enabled) {
            state.eventData.ts_reward_url = undefined;
            state.eventData.video_url = undefined;
            if (state.eventData.paid_event?.has_payment) {
              state.eventData.paid_event.has_nft = false;
              state.eventData.paid_event.ticket_type = "TICKET";
              state.eventData.paid_event.nft_image_url = undefined;
              state.eventData.paid_event.nft_video_url = undefined;
              state.eventData.paid_event.nft_title = undefined;
              state.eventData.paid_event.nft_description = undefined;
            }
          } else {
            if (state.eventData.paid_event?.has_payment) {
              state.eventData.paid_event.has_nft = true;
              state.eventData.paid_event.ticket_type = "NFT";
            }
          }
        });
      },
      setHasWeb3: (enabled: boolean) => {
        set((state) => {
          state.eventData.has_web3 = enabled;
          if (!enabled) {
            state.eventData.ts_reward_url = undefined;
            state.eventData.video_url = undefined;
            if (state.eventData.paid_event?.has_payment) {
              state.eventData.paid_event.has_nft = false;
              state.eventData.paid_event.ticket_type = "TICKET";
              state.eventData.paid_event.nft_image_url = undefined;
              state.eventData.paid_event.nft_video_url = undefined;
              state.eventData.paid_event.nft_title = undefined;
              state.eventData.paid_event.nft_description = undefined;
            }
          } else {
            if (state.eventData.paid_event?.has_payment) {
              state.eventData.paid_event.has_nft = true;
              state.eventData.paid_event.ticket_type = "NFT";
            }
          }
        });
      },
      togglePaidEvent: () => {
        set((state) => {
          const hasPayment = !state.eventData?.paid_event?.has_payment;
          const hasWeb3 = Boolean(state.eventData.has_web3);
          const paidEventInfo = {
            ...state.eventData?.paid_event,
            has_payment: hasPayment,
            has_nft: hasWeb3,
            token_id: state.eventData?.paid_event?.token_id ?? 1,
            ticket_type: hasWeb3 ? "NFT" : "TICKET",
            payment_amount: state.eventData?.paid_event?.payment_amount ?? 1,
          } as Partial<PaidEventType>;

          state.eventData.paid_event = paidEventInfo;
          if (hasPayment) {
            state.eventData.has_registration = true;
            state.eventData.capacity = state.eventData.capacity || 5;
          } else {
            if (state.eventData.eventLocationType === "in_person") {
              state.eventData.has_registration = true;
              state.eventData.capacity =
                state.eventData.capacity && state.eventData.capacity >= 1 ? state.eventData.capacity : 100;
            } else {
              state.eventData.capacity = null;
            }
          }
        });
      },
      changePaymentToken(tokenId) {
        set((state) => {
          state.eventData.paid_event.token_id = tokenId;
          if (!state.eventData.paid_event.payment_amount) {
            state.eventData.paid_event.payment_amount = 1;
          }
        });
      },
      changePaymentAmount(amount: number) {
        const handledValue = isNaN(amount) ? undefined : amount < 0 ? Math.abs(amount) : amount;

        set((state) => {
          state.eventData.paid_event.payment_amount = handledValue;
        });
      },
      changeTicketType(ticketType) {
        set((state) => {
          state.eventData.paid_event.ticket_type = ticketType;
        });
      },
      changeNFTImage(image) {
        set((state) => {
          state.eventData.paid_event.nft_image_url = image;
        });
      },
      changeNFTVideo(video) {
        set((state) => {
          state.eventData.paid_event.nft_video_url = video;
        });
      },
      changeNFTTitle: (title) => {
        set((state) => {
          state.eventData.paid_event.nft_title = title;
        });
      },
      changeNFTDescription: (desc) => {
        set((state) => {
          state.eventData.paid_event.nft_description = desc;
        });
      },
      setPaidInfoErrors: (key, value) => {
        set((state) => {
          state.paid_info_errors[key] = value;
        });
      },
      registrationStepMainButtonClick: () => {
        const { eventData, setCurrentStep } = get();
        const { paid_event, capacity } = eventData;

        const hasPayment = paid_event?.has_payment;

        if (hasPayment) {
          // Validate Paid Event Data
          const paymentParsed = PaidEventSchema.safeParse({
            ...paid_event,
            payment_amount: Number(paid_event.payment_amount!),
          });

          if (paymentParsed.error) {
            const fieldErrors = paymentParsed.error.flatten().fieldErrors;
            console.log("Validation Errors:", fieldErrors);
            set((state) => {
              state.paid_info_errors = fieldErrors;
            });
          } else {
            // Validation successful, proceed to the next step
            set((state) => {
              state.paid_info_errors = {};
            });
            console.log("Recipient Address:", paid_event.payment_recipient_address);
            console.log("Capacity:", capacity);
            setCurrentStep(4);
          }
        } else {
          // Handle Registration Only (No Payment)
          set((state) => {
            state.paid_info_errors = {};
          });
          setCurrentStep(4);
        }
      },
    }))
  )
);
