version: '3.8'

x-common-env: &common-env
  ENV: ${ENV}
  NODE_ENV: ${NODE_ENV}
  NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV}
  BRANCH_NAME: ${BRANCH_NAME}
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_URL_NFT_MANAGER: ${DATABASE_URL_NFT_MANAGER}
  REDIS_URL: ${REDIS_URL}
  TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  SOCIETY_HUB_API_KEY: ${SOCIETY_HUB_API_KEY}
  SOCIETY_HUB_ADMIN_CHAT_ID: ${SOCIETY_HUB_ADMIN_CHAT_ID}
  SOCIETY_HUB_CHAT_ID: ${SOCIETY_HUB_CHAT_ID}

x-default-extra-hosts: &default-extra-hosts
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  mini-app:
    image: ghcr.io/executesg/onton/mini-app:${BRANCH_NAME}-latest
    hostname: mini-app
    ports:
      - "${MINI_APP_PORT}:${MINI_APP_PORT}"
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  telegram-bot:
    image: ghcr.io/executesg/onton/telegram-bot:${BRANCH_NAME}-latest
    hostname: telegram-bot
    <<: *default-extra-hosts
    deploy:
      mode: global
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-ordinary-worker:
    image: ghcr.io/executesg/onton/mini-app-ordinary-worker:${BRANCH_NAME}-latest
    hostname: mini-app-ordinary-worker
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-reward-worker:
    image: ghcr.io/executesg/onton/mini-app-reward-worker:${BRANCH_NAME}-latest
    hostname: mini-app-reward-worker
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-poa-worker:
    image: ghcr.io/executesg/onton/mini-app-poa-worker:${BRANCH_NAME}-latest
    hostname: mini-app-poa-worker
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-sbt-worker:
    image: ghcr.io/executesg/onton/mini-app-sbt-worker:${BRANCH_NAME}-latest
    hostname: mini-app-sbt-worker
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-nft-api-worker:
    image: ghcr.io/executesg/onton/mini-app-nft-api-worker:${BRANCH_NAME}-latest
    hostname: mini-app-nft-api-worker
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-moderation-bot:
    image: ghcr.io/executesg/onton/mini-app-moderation-bot:${BRANCH_NAME}-latest
    hostname: mini-app-moderation-bot
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  mini-app-notification-socket:
    image: ghcr.io/executesg/onton/mini-app-notification-socket:${BRANCH_NAME}-latest
    hostname: mini-app-notification-socket
    ports:
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.2"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  website:
    image: ghcr.io/executesg/onton/website:${BRANCH_NAME}-latest
    hostname: website
    ports:
      - "${PORT_WEB_SITE}:${PORT_WEB_SITE}"
    <<: *default-extra-hosts
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
      replicas: 1
    environment:
      <<: *common-env
    networks:
      - onton-network

  caddy:
    image: ghcr.io/executesg/onton/caddy:${BRANCH_NAME}-latest
    hostname: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - fluentd
    deploy:
      resources:
        limits:
          memory: 6000M
          cpus: '4.0'
      mode: global
      update_config:
        failure_action: rollback
        order: start-first
      placement:
        constraints:
          - node.role == manager
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /home/tonont/caddy/dev.caddyfile:/etc/caddy/Caddyfile:ro
      - ./devops/cert/:/certs
    networks:
      - onton-network
    environment:
      <<: *common-env
      USE_CLOUDFLARE: ${USE_CLOUDFLARE}
      CLOUDFLARE_EMAIL: ${CLOUDFLARE_EMAIL:-}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN:-}
      CLOUDFLARE_EMAIL_MAIN: ${CLOUDFLARE_EMAIL_MAIN:-}
      CLOUDFLARE_API_TOKEN_MAIN: ${CLOUDFLARE_API_TOKEN_MAIN:-}
    secrets:
      - registry-onton-config

  registry:
    image: registry:latest
    hostname: registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      SHOW_CONTENT_DIGEST: "true"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - /home/tonont/registry/registry.password:/auth/registry.password
      - registry_data:/data
    deploy:
      mode: global
      resources:
        limits:
          memory: 4000M
          cpus: '2.0'
    networks:
      - onton-network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    hostname: registry-ui
    environment:
      REGISTRY_TITLE: "ONTON Docker Registry UI"
      NGINX_PROXY_PASS_URL: "http://registry:5000"
      DELETE_IMAGES: "true"
    networks:
      - onton-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.0'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - onton-network

  fluentd:
    image: fluent/fluentd:v1.18-debian-1
    hostname: fluentd
    user: root
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.2'
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./devops/fluent/fluent.conf:/fluentd/etc/fluent.conf
    entrypoint: >
      /bin/sh -c "
      apt-get update -y &&
      apt-get install curl -y &&
      gem install fluent-plugin-concat &&
      gem install fluent-plugin-elasticsearch  &&
      gem install fluent-plugin-prometheus &&
      gem install fluent-plugin-prometheus-pull &&
      fluentd -c /fluentd/etc/fluent.conf -v
      "
    environment:
      FLUENT_ELASTICSEARCH_HOST: elasticsearch
      FLUENT_ELASTICSEARCH_PORT: 9200
    depends_on:
      - elasticsearch
    networks:
      - onton-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    hostname: swagger-ui
    ports:
      - "${SWAGGER_UI_PORT}:8080"
    environment:
      <<: *common-env
      SWAGGER_JSON: "/swagger.yaml"
    volumes:
      - ./swagger/ExternalSeller.yml:/usr/share/nginx/html/swagger/ExternalSeller.yaml
      - ./swagger/GameRewards.yml:/usr/share/nginx/html/swagger/GameRewards.yaml
      - ./swagger/NFTApi.yml:/usr/share/nginx/html/swagger/NFTApi.yaml
      - ./swagger/swagger-initializer.js:/usr/share/nginx/html/swagger-initializer.js
      - ./swagger/custom.css:/usr/share/nginx/html/swagger/custom.css
    networks:
      - onton-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  onton-network:
    name: onton-network-${BRANCH_NAME}
    driver: overlay
    external: true

volumes:
  caddy_data:
    name: "${BRANCH_NAME}_caddy_data"
  caddy_config:
    name: "${BRANCH_NAME}_caddy_config"
  registry_data:
    name: "${BRANCH_NAME}_registry_data"
  elasticsearch_data:
    name: "${BRANCH_NAME}_elasticsearch_data"
  minio_data:
    name: "${BRANCH_NAME}_minio_data"
  postgres_data:
    name: "${BRANCH_NAME}_postgres_data"
  redis_data:
    name: "${BRANCH_NAME}_redis_data"
  drizzle_data:
    name: "${BRANCH_NAME}_drizzle_data"
  drizzle_data_cron:
    name: "${BRANCH_NAME}_drizzle_data_cron"

secrets:
  registry-onton-config:
    external: true
