import fs from "fs";
import path from "path";
import { marked } from "marked";

const CONTENT_DIR = path.join(process.cwd(), "src", "content");
const MANIFEST_PATH = path.join(CONTENT_DIR, "manifest.json");

/**
 * Loads the pre-built manifest generated by sync_content.py,
 * or falls back to parsing directly from disk.
 */
export function getManifest() {
  if (fs.existsSync(MANIFEST_PATH)) {
    try {
      const raw = fs.readFileSync(MANIFEST_PATH, "utf-8");
      return JSON.parse(raw);
    } catch (e) {
      console.error("Error reading manifest.json:", e);
    }
  }
  return { articles: [], glossary: [], events: [] };
}

export function getAllArticles() {
  const manifest = getManifest();
  return (manifest.articles || []).sort(
    (a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0)
  );
}

export function getAllArticleSlugs() {
  const articles = getAllArticles();
  return articles.map((article) => article.slug);
}

export function getArticleBySlug(slug) {
  const articles = getAllArticles();
  return articles.find((a) => a.slug === slug) || null;
}

export function getFeaturedArticles() {
  const articles = getAllArticles();
  return articles.filter((a) => a.featured || a.category === "Telegram Stars");
}

export function getRelatedArticles(currentSlug, category, limit = 3) {
  const articles = getAllArticles();
  return articles
    .filter((a) => a.slug !== currentSlug && (a.category === category || true))
    .slice(0, limit);
}

export function getAllGlossaryTerms() {
  const manifest = getManifest();
  return (manifest.glossary || []).sort((a, b) =>
    (a.term || a.title).localeCompare(b.term || b.title)
  );
}

export function getAllGlossarySlugs() {
  const terms = getAllGlossaryTerms();
  return terms.map((t) => t.slug);
}

export function getGlossaryTermBySlug(slug) {
  const terms = getAllGlossaryTerms();
  return terms.find((t) => t.slug === slug) || null;
}

export function getAllEvents() {
  const manifest = getManifest();
  return (manifest.events || []).sort(
    (a, b) => new Date(a.startDate || 0) - new Date(b.startDate || 0)
  );
}

export function getAllEventSlugs() {
  const events = getAllEvents();
  return events.map((e) => e.slug);
}

export function getEventBySlug(slug) {
  const events = getAllEvents();
  return events.find((e) => e.slug === slug) || null;
}

/**
 * Extracts H2 and H3 headings for the sticky Table of Contents (TOC).
 */
export function extractHeadings(markdownContent) {
  const headingRegex = /^(#{2,3})\s+(.+)$/gm;
  const headings = [];
  let match;

  while ((match = headingRegex.exec(markdownContent)) !== null) {
    const level = match[1].length; // 2 for H2, 3 for H3
    const text = match[2].trim().replace(/\*\*/g, "").replace(/`/g, "");
    const id = text
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .replace(/\s+/g, "-");

    headings.push({ level, text, id });
  }

  return headings;
}

/**
 * Renders Markdown to HTML with enhanced responsive elements and anchor links.
 */
export async function renderMarkdown(markdownContent) {
  const processed = markdownContent.replace(/^(#{2,3})\s+(.+)$/gm, (match, hashes, text) => {
    const cleanText = text.trim().replace(/\*\*/g, "").replace(/`/g, "");
    const id = cleanText
      .toLowerCase()
      .replace(/[^\w\s-]/g, "")
      .replace(/\s+/g, "-");
    return `${hashes} <span id="${id}"></span>${text}`;
  });

  return marked.parse(processed, { gfm: true, breaks: true });
}
